# Generated by Django 4.0.4 on 2022-06-26 02:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.CharField(default=uuid.UUID('d7eacd9c-a7ee-4bb3-b4a6-e44c373ac920'), max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.CharField(default=uuid.UUID('8bf66c28-1f30-433e-85ce-4b772cb95521'), max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('zona', models.CharField(max_length=30)),
                ('public', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.CharField(default=uuid.UUID('398c0977-912d-43de-a438-cb70e3a55d4f'), max_length=40, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('matrícula', models.CharField(max_length=15)),
                ('edad', models.IntegerField(max_length=3)),
                ('email', models.EmailField(max_length=254)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHospital.especialidad')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHospital.hospital')),
            ],
        ),
    ]
