# Generated by Django 4.0.4 on 2022-07-04 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appHospital', '0002_blog_alter_especialidad_id_alter_hospital_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('publicado',)},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='fecha',
        ),
        migrations.AddField(
            model_name='blog',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado')], default='borrador', max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='excerpt',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='publicado',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(editable=False, max_length=250, unique=True, unique_for_date='publicado'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='subtitulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='id',
            field=models.CharField(default=uuid.UUID('4471d1ea-3e5b-4900-adb8-13a27889b6eb'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.CharField(default=uuid.UUID('7f781f9f-a4ac-4490-9c3f-0f97761b4d75'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='id',
            field=models.CharField(default=uuid.UUID('05009cab-fcac-43d5-9d1b-b0bd3d612648'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contenido', models.TextField()),
                ('publicado', models.DateTimeField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='appHospital.blog')),
            ],
            options={
                'ordering': ('publicado',),
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='appHospital.categoria'),
        ),
    ]
