# Generated by Django 4.0.4 on 2022-07-04 05:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0003_categoria_alter_blog_options_remove_blog_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=250, unique=True, unique_for_date='publicado'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='id',
            field=models.CharField(default=uuid.UUID('033b5106-a2e4-4684-9eb9-c4b7c4b663f7'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.CharField(default=uuid.UUID('0f2c91a6-3c68-4b92-8b95-739fb3b58dfd'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='id',
            field=models.CharField(default=uuid.UUID('26751863-34a6-422f-aa96-ee24ab54d8a5'), max_length=40, primary_key=True, serialize=False),
        ),
    ]
