# Generated by Django 4.0.4 on 2022-07-04 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0005_blog_image_alter_especialidad_id_alter_hospital_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='none.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='id',
            field=models.CharField(default=uuid.UUID('338526e3-a7ec-4776-93d9-393106f3527b'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.CharField(default=uuid.UUID('d694586a-a9bb-4443-8987-25ad6bee2e0c'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='id',
            field=models.CharField(default=uuid.UUID('cca1e25f-58ab-4110-a854-beb49dbc3bd7'), max_length=40, primary_key=True, serialize=False),
        ),
    ]
