# Generated by Django 4.0.4 on 2022-07-04 09:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appHospital', '0006_alter_blog_image_alter_especialidad_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='id',
            field=models.CharField(default=uuid.UUID('2e599476-2ee6-44f8-824c-e1aadcc2c0d9'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.CharField(default=uuid.UUID('6fd03130-ff8f-4dc5-aad4-c98001c9e341'), max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='id',
            field=models.CharField(default=uuid.UUID('680399b1-5118-4856-ba34-cd3c52d8fed1'), max_length=40, primary_key=True, serialize=False),
        ),
    ]
